Layout
genialis/dictyexpress-js pull request #11
Opened 2020-11-09 13:21 UTC by zigasinko

2021-01-06 09:32 UTC, janybravo requested changes

2021-01-06 09:32 UTC, janybravo commented on src/components/app/app.tsx
> +// CSRF cookie has to be obtained in order to send any request to API.
I dont see need for comment as api names explains it all to me.

2021-01-06 09:32 UTC, janybravo commented on src/components/genexpress/common/constants.ts
> +export const ModulesKeys = {
Here should be enums. Consider using enums for new code.

2021-01-06 09:32 UTC, janybravo commented on src/components/genexpress/genexpressAppBar/genexpressAppBar.tsx
> +    const handleDefaultLayoutClick = (): void => {
Redundant :void type. Also consider putting it to JSX  as its trivial function.

2021-01-06 09:32 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSets/geneSetSelector.tsx
> +    const handleSaveOnClick = (): void => {
Redundant :void, applies to the rest of cases in this PR.

2021-01-06 09:32 UTC, janybravo commented on src/components/genexpress/geneExpressGrid.tsx
> +        /* react-grid-layout has a bug for mutating prop on item resize:
This is a good comment!

2021-01-06 09:32 UTC, janybravo commented on src/components/genexpress/geneExpressGrid.tsx
> +    /**
This is actually long secondary description of "handleOnLayoutChange" therefore redundant event for me.

2021-01-06 09:32 UTC, janybravo commented on src/redux/epics/layoutsEpics.ts
> +// eslint-disable-next-line import/prefer-default-export
I think this should be added to .eslint config.

2021-01-06 09:32 UTC, janybravo commented on src/redux/epics/layoutsEpics.ts
> +export const layoutsChangedEpic: Epic<Action, Action, RootState> = (action$) =>
I suppose $ is denoting object is something of RxJS api. We have TS types for that, we should not decorate variables with $_ with few exceptions.

2021-01-06 09:32 UTC, janybravo commented on src/components/genexpress/geneExpressGrid.tsx
> +import _ from 'lodash';
import only deepClone from 'lodash/x', for better code clarity and explicitness

2021-01-06 09:32 UTC, janybravo commented on src/redux/models/internal.ts
> +export type BreakpointsCols = { lg: number; md: number; sm: number };
Consider Record<'lg'|'md'|'sm', number>

2021-01-06 09:32 UTC, janybravo commented on src/redux/models/internal.ts
> +export type BreakpointsCols = { lg: number; md: number; sm: number };
Perhaps have expanded keys 'lg' ...  'large'

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +/* eslint no-param-reassign: ["error", { "props": false }] */
I think we should not ignore this as it prevents variable content mixing therefore inforces cleaner code.

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +/**
redundant

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +import _ from 'lodash';
import each function

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +    const widthInCols = _.get(width, breakpoint) ?? width;
Don't do this. there is no static type checking here. use optional chaining if there are null concerens.

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +    // If there's no more space in current row, move module to the next row.
Good comment!

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +        // If there's enough space in current row, place module in it and subtract available space.
good comment

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +    currentRowInfo.availableSpaceInCols += -widthInCols;
currentRowInfo.availableSpaceInCols -= widthInCols; should be enough

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +/**
redundant

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +// State slices.
redundant

2021-01-06 09:32 UTC, janybravo commented on src/redux/stores/layouts.ts
> +    lg: getBreakpointLayouts('lg'),
IMplement enum  as argument eg. LayoutBreakpoints.Large

2021-01-06 13:09 UTC, zigasinko commented on src/components/app/app.tsx
> +// CSRF cookie has to be obtained in order to send any request to API.
True, removed.

2021-01-06 14:21 UTC, zigasinko commented on src/components/genexpress/common/constants.ts
> +export const ModulesKeys = {
Added a commit to refactor all constants to TypeScript string enums.

2021-01-06 14:23 UTC, zigasinko commented on src/components/genexpress/genexpressAppBar/genexpressAppBar.tsx
> +    const handleDefaultLayoutClick = (): void => {
I've written all lint suggestions to a document and we'll address this once all pull requests are merged.

2021-01-06 14:24 UTC, zigasinko commented on src/components/genexpress/geneExpressGrid.tsx
> +        /* react-grid-layout has a bug for mutating prop on item resize:
And this is a good review comment :D Thanks!

2021-01-06 14:40 UTC, zigasinko commented on src/components/genexpress/geneExpressGrid.tsx
> +    /**
Removed.

2021-01-06 14:45 UTC, zigasinko commented on src/redux/epics/layoutsEpics.ts
> +export const layoutsChangedEpic: Epic<Action, Action, RootState> = (action$) =>
This is a suggested way of writing epics by redux-observable team. I'm also for this approach because it's clear what it is without mouse hover and naming clashes that can happen, e.g.:
![image](https://user-images.githubusercontent.com/26134756/103781011-0f4b9600-5036-11eb-82b8-40647651446d.png)

We can discuss this further for the new front end.

2021-01-06 15:00 UTC, zigasinko commented on src/components/genexpress/geneExpressGrid.tsx
> +import _ from 'lodash';
I think using lodash functions directly by their name is less explicit.

Example `_.mean([])` is more explicit than `mean([])` -> dicty has it's own mean function and you have to hover over it to know where it comes from.

Apart from that, importing only from specific lodash modules improves bundle size. With gzip that's not a lot but still.. I've written this task down and will do it after all PRs are merged because there's a lot of commits and all of them are using lodash functions in this way.

2021-01-06 15:16 UTC, zigasinko commented on src/redux/models/internal.ts
> +export type BreakpointsCols = { lg: number; md: number; sm: number };
Using TypeScript utility `Record` makes it more difficult to refactor things. Like expanding keys. So I've left it and only expanded the keys.

2021-01-06 15:27 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +/* eslint no-param-reassign: ["error", { "props": false }] */
For this example, code is cleaner with disabled rule, otherwise we'd have to carry over `currentRowInfo` for each module. I've moved disable rule to specific lines in `generateModuleLayout` function so that potential new functions aren't affected.

2021-01-06 15:28 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +/**
Removed.

2021-01-06 15:38 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +    const widthInCols = _.get(width, breakpoint) ?? width;
That's not possible because width can be either a `number `or a `{large: 12, mid: 10, small: 6,}` type. Because either a number or an object is always passed I can manually assert `widthInCols` as a number. What do you think about this solution?

E.g.: `const widthInCols = (_.get(width, breakpoint) ?? width) as number;`.

2021-01-06 15:38 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +    currentRowInfo.availableSpaceInCols += -widthInCols;
Nice one!

2021-01-06 15:39 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +/**
Removed.

2021-01-06 15:40 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +// State slices.
Removed. I'll remove all other redundant store comments with each pull request so please keep marking them.

2021-01-06 15:46 UTC, janybravo commented on src/redux/epics/layoutsEpics.ts
> +export const layoutsChangedEpic: Epic<Action, Action, RootState> = (action$) =>
Lets stick to $ as it indicates RxJS stream with similar naming as redux objects

2021-01-06 16:01 UTC, janybravo commented on src/redux/stores/layouts.ts
> +    const widthInCols = _.get(width, breakpoint) ?? width;
Oh i missed that. Dual type can be confusing.  It can easily be avoided here and only use number. Move key selection up.

2021-01-06 16:02 UTC, janybravo commented on src/redux/stores/layouts.ts
> +    const widthInCols = _.get(width, breakpoint) ?? width;
I think its better to have clean simpler interface and code checked by TSC instead.

2021-01-06 17:17 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +    lg: getBreakpointLayouts('lg'),
Yup, smart. Done.

2021-01-06 17:21 UTC, zigasinko commented on src/redux/stores/layouts.ts
> +    const widthInCols = _.get(width, breakpoint) ?? width;
Of course.. thanks. Fix'd

2021-01-07 10:29 UTC, janybravo requested changes

2021-01-07 10:29 UTC, janybravo commented on src/components/genexpress/common/constants.ts
> +    geneSets = 'geneSets',
As far as me, you done need to have same name as value.

2021-01-07 10:29 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/selectedGenes/selectedGenes.spec.tsx
> +    species: 'Dictyostelium purpureum',
I think here should be enums

2021-01-07 11:04 UTC, zigasinko commented on src/components/genexpress/common/constants.ts
> +    geneSets = 'geneSets',
Changed it just to keep it consistent with other enums.

2021-01-07 11:07 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/selectedGenes/selectedGenes.spec.tsx
> +    species: 'Dictyostelium purpureum',
Frontend doesn't need any knowledge about possible sources or species. All these data comes from backed when adding samples to the basket (on timeSeries select). So this two values could be anything really.

2021-01-07 11:50 UTC, janybravo approved these changes

2021-01-07 11:51 UTC, merged