Gene ontology
genialis/dictyexpress-js pull request #12
Opened 2020-11-09 16:17 UTC by zigasinko

2021-01-07 12:08 UTC, janybravo requested changes

2021-01-07 12:08 UTC, janybravo commented on src/api/dataApi.ts
> +const handleGOEnrichmentAnalysisDataResponse = (
This is a bit confusing for me as name starts with "handle" but it actualy returns PayloadAction or null and we need comment to explain interface and some of its logic? Change naming making comment redundant.

2021-01-07 12:08 UTC, janybravo commented on src/api/featureApi.ts
> +    // Species property won't be included if it's null.
this should't be neccessary

2021-01-07 12:08 UTC, janybravo commented on src/api/fetch.ts
> +    getReactive,
these should all be exported one by one for better modularity that you dont get by wrapping into object literals.

2021-01-07 12:08 UTC, janybravo commented on src/api/queryObserverManager.ts
> + * a new message with the same observe guid.
remove comment and improve function naming and TS interface for query function to have information from this comment

2021-01-07 12:08 UTC, janybravo commented on src/api/base.ts
> +export const sessionId = uuidv4();
Consider separate index file for api that gathers all exports from theese "api" files.

2021-01-07 12:08 UTC, janybravo commented on src/components/app/app.tsx
> +// CSRF cookie has to be obtained in order to send any request to API.
We already discussed this

2021-01-07 12:08 UTC, janybravo commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +/**
remove

2021-01-07 12:08 UTC, janybravo commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +const defaultColDef = {
is that defaultColumnDefinition? lets expand name

2021-01-07 12:08 UTC, janybravo commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +    // Destroy grid after component is unmounted.
remove aplicable to the rest of such

2021-01-07 15:33 UTC, janybravo requested changes

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.style.ts
> +    & img {
& is not needed. Another detail is probably not a problem in this particular case but in are in general. plain tag selectors are considered as bad practise since they lead to selector clashes and lesss roboust code..

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.tsx
> +    const columnDefs = useRef([
move on root scope of this es module as regular object, no need for useRef

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.tsx
> +                        <span>{_.capitalize(gOEnrichmentRow.term_name)}</span>
Use css text-transform for that

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    const handleOnSortChanged = (event: SortChangedEvent): void => {
Name should describe what this does as we can assume that is a "handler" when is assigned to prop. and comment becomes redundant

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    /**
see above

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +/**
remove

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +// Flatten the tree into rows.
see above

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +/**
see above

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +    // Filter by biological aspect.
see above

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +            item.score_percentage = (item.score / maxScore) * 100;
loosing precision here, do (item.score * 100) / maxScore

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.tsx
> +        // Display dropdown if there is anything in the input.
remove

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.tsx
> +        // Unfocus autocomplete element.
see above

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSets/manageGeneSetsModal.spec.tsx
> +// Needed to assert selected item with '~toggle Row Selection' (first row).
~ probably not needed

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSets/manageGeneSetsModal.tsx
> +    const columnDefs = useRef([
to root module scope, without useRef

2021-01-07 15:33 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/timeSeriesAndGeneSelector.tsx
> +    const columnDefs = useRef([
to root scope

2021-01-07 15:33 UTC, janybravo commented on src/redux/epics/authenticationEpics.ts
> +export default combineEpics(loginEpic, logoutEpic, getCurrentUserEpic);
I would revert whole file to previous. I dont think is better to have one big object for default  export

2021-01-07 15:33 UTC, janybravo commented on src/redux/epics/genesEpics.ts
> + * @param geneIds - IDs of genes that need to be .
remove

2021-01-07 15:33 UTC, janybravo commented on src/redux/epics/layoutsEpics.ts
> +export default layoutsChangedEpic;
previous better

2021-01-07 15:33 UTC, janybravo commented on src/redux/epics/timeSeriesEpics.ts
> +export default combineEpics(
as already mentioned

2021-01-07 15:33 UTC, janybravo commented on src/redux/models/rest.ts
> +
remove comment, convert to enum

2021-01-07 15:33 UTC, janybravo commented on src/tests/mock.ts
> +/**
that should be obvious from type, remove

2021-01-07 15:33 UTC, janybravo commented on src/tests/test-utils.tsx
> +/**
remove

2021-01-08 09:17 UTC, zigasinko commented on src/api/dataApi.ts
> +const handleGOEnrichmentAnalysisDataResponse = (
Changed the name to `getDataFetchSucceededActionIfDone` and removed the comment.

2021-01-08 09:18 UTC, zigasinko commented on src/api/featureApi.ts
> +    // Species property won't be included if it's null.
Removed.

2021-01-08 09:40 UTC, zigasinko commented on src/api/fetch.ts
> +    getReactive,
I agree and it was done this way at first. I changed it later because of Domen's suggestion to avoid disabling `import/prefer-default-export` rule. I've changed it in all places.

2021-01-08 11:24 UTC, zigasinko commented on src/api/queryObserverManager.ts
> + * a new message with the same observe guid.
Removed comment. Query already includes `observe` parameter so interface change is not necessary.

2021-01-08 13:03 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +/**
Removed.

2021-01-08 13:04 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +// Flatten the tree into rows.
Removed.

2021-01-08 13:04 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +/**
Removed.

2021-01-08 13:04 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +    // Filter by biological aspect.
Removed.

2021-01-08 13:05 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichmentUtils.ts
> +            item.score_percentage = (item.score / maxScore) * 100;
Copied from current frontend solution. Good find, thanks!

2021-01-08 13:06 UTC, zigasinko commented on src/redux/epics/genesEpics.ts
> + * @param geneIds - IDs of genes that need to be .
Removed.

2021-01-08 13:10 UTC, zigasinko commented on src/redux/models/rest.ts
> +
Removed the whole structure and used the one from resolwe-js.

2021-01-08 13:10 UTC, zigasinko commented on src/tests/mock.ts
> +/**
Removed.

2021-01-08 13:11 UTC, zigasinko commented on src/tests/test-utils.tsx
> +/**
Removed.

2021-01-08 13:18 UTC, zigasinko commented on src/api/base.ts
> +export const sessionId = uuidv4();
Good one! I've created an index file for all `api` files and used it's import everwhere.

2021-01-08 13:22 UTC, zigasinko commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +/**
I think it adds value because of the warning that ag-grid will get reinitialized when `columnDefs` change. So I'd rather leave it.

2021-01-08 13:22 UTC, zigasinko commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +const defaultColDef = {
Synced with other `columnDefs `-> `defaultColumnDef`.

2021-01-08 13:24 UTC, zigasinko commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +    // Destroy grid after component is unmounted.
Removed all except the `columnDefs useEffect` and `setSelectedData` which are useful in my opinion.

2021-01-08 13:52 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.tsx
> +        // Display dropdown if there is anything in the input.
Removed.

2021-01-08 13:54 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.style.ts
> +    & img {
Good tip. I ended up adding a new styled-component `AmigoLinkImage` for this `img` element.

2021-01-08 13:55 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.tsx
> +    const columnDefs = useRef([
I've written this down and will fix it in all places after all PRs are merged, because this approach was used for all grids..

2021-01-08 13:58 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.tsx
> +                        <span>{_.capitalize(gOEnrichmentRow.term_name)}</span>
Done.

2021-01-08 14:01 UTC, janybravo commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +/**
Why do you think its valuable? in react everyting is subject to re-render when prop's instance differs, what's different in this case - that would add value for yout comment. Reinitialize means remount  ?

2021-01-08 14:03 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    const handleOnSortChanged = (event: SortChangedEvent): void => {
Renamed to `onSortChangedHandler` and removed function comment.

2021-01-08 14:04 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    /**
Renamed to `onMatchedGenesClickHandler` and removed the comment.

2021-01-08 14:05 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.tsx
> +        // Unfocus autocomplete element.
Removed.

2021-01-08 14:10 UTC, janybravo commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +    // Destroy grid after component is unmounted.
"Destroy grid after component is unmounted." What is information of that for you? for me is none really as code is very explicit?

2021-01-08 14:23 UTC, zigasinko commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +/**
Yeah but all other properties get handled by ag-grid so that it doesn't have to be reinitialized. If `columnDefs` change, dictyGrid key will change which means ag-grid will be reinitialized - remounted yes.

2021-01-08 14:48 UTC, janybravo commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +/**
Then only annotate `columnDefs` field by  placing onliner comment above that. `AgGrid will remount if columnDefs change, so make sure you pass column definitions with a persistent object (e.g. useRef).` moving relevant code closer.

2021-01-08 14:50 UTC, zigasinko commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +    // Destroy grid after component is unmounted.
This one was removed, commit incoming!

2021-01-08 14:51 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSets/manageGeneSetsModal.spec.tsx
> +// Needed to assert selected item with '~toggle Row Selection' (first row).
The text is not exact and it got changed once already with new ag-grid version. That's why I used the `~`.

2021-01-08 14:51 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSets/manageGeneSetsModal.tsx
> +    const columnDefs = useRef([
Written a TODO for this.

2021-01-08 14:51 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/timeSeriesAndGeneSelector.tsx
> +    const columnDefs = useRef([
Written a todo.

2021-01-08 14:53 UTC, zigasinko commented on src/redux/epics/authenticationEpics.ts
> +export default combineEpics(loginEpic, logoutEpic, getCurrentUserEpic);
Epics get combined in the same fashion with individual exports or like this. I'd prefer to have feature epics combined so that we don't have to include each new one in rootEpic.

2021-01-08 15:16 UTC, zigasinko commented on src/redux/epics/layoutsEpics.ts
> +export default layoutsChangedEpic;
Look above.

2021-01-08 15:16 UTC, zigasinko commented on src/redux/epics/timeSeriesEpics.ts
> +export default combineEpics(
Look above.

2021-01-08 15:52 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +                            columnDefs={[
this is remount on each render as described at DictyGrid. I suppose that is not preferred behavior.

2021-01-08 16:49 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    const handleOnSortChanged = (event: SortChangedEvent): void => {
no difference. `changeSort` is what your fucntion do and whats passed as onChangeHandler.

2021-01-08 16:50 UTC, janybravo commented on src/redux/epics/authenticationEpics.ts
> +export default combineEpics(loginEpic, logoutEpic, getCurrentUserEpic);
yes, have it that way as already discussed

2021-01-08 16:57 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    /**
what about, selectAndOpenModal

2021-01-11 16:22 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    const handleOnSortChanged = (event: SortChangedEvent): void => {
Let's talk about this on tuesday. This is a principle used in all components. The suggestion is good but I'd like to have a consistent codebase which means refactoring handlers names in all components.

2021-01-11 16:22 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    /**
^^same as the comment above

2021-01-11 16:36 UTC, zigasinko commented on src/components/genexpress/common/dictyGrid/dictyGrid.tsx
> +/**
Good idea. I've moved the column to `DictyGridProps` type (comment above `columnDefs` property).

2021-01-12 09:06 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    const handleOnSortChanged = (event: SortChangedEvent): void => {
OK, I'll skip such PR comment in the future until refactoring PR that would address all of those

2021-01-12 09:09 UTC, janybravo approved these changes

2021-01-12 09:11 UTC, merged