Export
genialis/dictyexpress-js pull request #13
Opened 2020-11-15 16:30 UTC by zigasinko

Implemented export functionality.

2021-01-12 14:50 UTC, janybravo requested changes
Threre are mostly redundant comments and few redability and UX improvement suggestions.

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/chart/chart.tsx
> +    /**
remove this na following 2 comments, add  exeption throw if this is really concerning:  "Method expects chartView to be initialized so only call it once "getChartView" is not null."

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/chart/chart.tsx
> +// ForwardRefRenderFunction type is used so that "ChartHandle" type is ful.
"ChartHandle" type is ful. what does that mean? ForwardRefRenderFunction type should probably be enough,

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.integration.spec.tsx
> +// eslint-disable-next-line import/prefer-default-export
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.integration.spec.tsx
> +        // Export button in app bar.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.integration.spec.tsx
> +        // Export button in prefix modal.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
remove, example is the code using this function

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> +    alert(
this is bad UX. app should inform user before it clicks on download and be disapointed by results due to wierd browser

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> +    alert(
and since when is this problem. perhaps is already irrelevant today, check please.

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> +        browser.getBrowserName() === 'safari' && !browser.satisfies({ safari: '>=10.1' });
this is 4 years old, do we really need this ?

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
remove, update file name

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> +    const componentsReportsPromises = _.map(registeredComponents, async (getReport) => {
why is not Array.prototype.map enough ?

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/useReport.ts
> +import { useEffect } from 'react';
This seems all just for avoiding lint rule "react-hooks/exhaustive-deps" as comment suggests. is that correct?

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/genexpressAppBar/genexpressAppBar.tsx
> +    const areExportingModulesLoading =
Thats should show spinner icon somewhere to better indicate operation in progress.

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/differentialExpressions/differentialExpressions.integration.spec.tsx
> +import { validateExportFile } from 'components/genexpress/common/reportBuilder/reportBuilder.integration.spec';
this is not wise. export to common "test utils"

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/differentialExpressions/differentialExpressions.tsx
> +    // Register reportBuilder getComponentReport function.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/differentialExpressions/differentialExpressions.tsx
> +            // no volcanoPoints are empty.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/differentialExpressions/differentialExpressionsVolcanoPlot.tsx
> +                {
extract big jsons to util factory function for better readability of this component

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.spec.tsx
> +import { validateExportFile } from 'components/genexpress/common/reportBuilder/reportBuilder.integration.spec';
extract to common util

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    // Register reportBuilder getComponentReport function.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/geneExpressions/geneExpressions.tsx
> +    // Register reportBuilder getComponentReport function.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/geneExpressions/geneExpressionsLineChart.tsx
> +        // Data handlers that is updated (and reattached) only if highlighted variable changes.
remove and check useMemo as react doc for assumption here - useMemo can change in the future versions.

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/geneExpressions/geneExpressionsLineChart.tsx
> +            signals: [
consider exporting jsons to util factory function

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.spec.tsx
> +import { validateExportFile } from 'components/genexpress/common/reportBuilder/reportBuilder.integration.spec';
extract

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.spec.tsx
> +        it('should export empty Genes/selected_genes.tsv file', async () => {
UX objection here - its better to disable export when result would be usless. Please add improvement task.

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.tsx
> +    // Register reportBuilder getComponentReport function.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/timeSeriesAndGeneSelector.tsx
> +    // Register reportBuilder getComponentReport function.
remove

2021-01-12 14:50 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/timeSeriesAndGeneSelector.tsx
> +                selectedTimeSeries != null
its more readable to  have selectedTimeSeries == null

2021-01-12 14:50 UTC, janybravo commented on src/utils/documentHelpers.ts
> + */
remove

2021-01-12 14:50 UTC, janybravo commented on src/utils/documentHelpers.ts
> +    // URL.revokeObjectURL(a.href);
remove

2021-01-12 14:50 UTC, janybravo commented on src/utils/gOEnrichmentUtils.ts
>   */
remove

2021-01-12 14:50 UTC, janybravo commented on src/utils/gOEnrichmentUtils.ts
> + */
remove

2021-01-12 14:50 UTC, janybravo commented on src/utils/reportUtils.ts
> +import _ from 'lodash';
all comments seems redundant to me

2021-01-12 17:29 UTC, zigasinko commented on src/components/genexpress/common/chart/chart.tsx
> +    /**
Removed comments and changed the way visualization export files are processed (if content is null, file is omitted).

2021-01-12 17:31 UTC, zigasinko commented on src/components/genexpress/common/chart/chart.tsx
> +// ForwardRefRenderFunction type is used so that "ChartHandle" type is ful.
Removed this comment, not sure where I was going with it..

2021-01-12 17:31 UTC, zigasinko commented on src/components/genexpress/common/reportBuilder/reportBuilder.integration.spec.tsx
> +// eslint-disable-next-line import/prefer-default-export
Removed.

2021-01-12 17:34 UTC, zigasinko commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
Removed the comment. Update which file name?

2021-01-12 17:39 UTC, zigasinko commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> +    const componentsReportsPromises = _.map(registeredComponents, async (getReport) => {
`registeredComponents` is `[id: string]: GetComponentReport;` type, not an array.

2021-01-12 17:43 UTC, zigasinko commented on src/components/genexpress/common/reportBuilder/useReport.ts
> +import { useEffect } from 'react';
No, this hook is used to register components to reportBuilder.
I've managed to add a custom rule to check for exhaustive-deps in `useReport` hook:
```
'react-hooks/exhaustive-deps': [
    'warn',
    {
        additionalHooks: '(useReport)',
    },
],
```
A great example why it's best to avoid commenting too much :) Removed the comment!

2021-01-12 17:44 UTC, zigasinko commented on src/components/genexpress/genexpressAppBar/genexpressAppBar.tsx
> +    const areExportingModulesLoading =
Loading bars are under modules title / grid loading indicator.

2021-01-12 17:47 UTC, zigasinko commented on src/components/genexpress/modules/differentialExpressions/differentialExpressions.integration.spec.tsx
> +import { validateExportFile } from 'components/genexpress/common/reportBuilder/reportBuilder.integration.spec';
Any special reason why this is not wise?

2021-01-12 17:48 UTC, zigasinko commented on src/components/genexpress/modules/differentialExpressions/differentialExpressions.tsx
> +    // Register reportBuilder getComponentReport function.
Removed this type of comment from all modules.

2021-01-12 17:49 UTC, zigasinko commented on src/components/genexpress/modules/differentialExpressions/differentialExpressionsVolcanoPlot.tsx
> +                {
Let's discuss this tomorrow.

2021-01-12 17:54 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelector/geneSelector.spec.tsx
> +        it('should export empty Genes/selected_genes.tsv file', async () => {
We'll have to check this with Miha B, because this is the way it's done currently. Maybe there's a specific need for it.

2021-01-12 17:55 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/timeSeriesAndGeneSelector.tsx
> +                selectedTimeSeries != null
Isn't it more intuitive to have the positive flow first?

2021-01-12 17:57 UTC, zigasinko commented on src/utils/reportUtils.ts
> +import _ from 'lodash';
But it's sooooooo pretty with green comment blocks :D Removed!

2021-01-13 07:53 UTC, janybravo commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
function name i meant, to be more descriptive

2021-01-13 08:04 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/timeSeriesAndGeneSelector.tsx
> +                selectedTimeSeries != null
that don't relate to cleanlessness while parsing conditions is

2021-01-13 08:12 UTC, janybravo commented on src/components/genexpress/modules/differentialExpressions/differentialExpressions.integration.spec.tsx
> +import { validateExportFile } from 'components/genexpress/common/reportBuilder/reportBuilder.integration.spec';
test should not export stuff to other tests this is good practise to have implement circular dependencies. we have utils or libraries or model for that.

2021-01-13 10:00 UTC, zigasinko commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> + */
Renamed to `getRegisteredComponentsExportFiles`.

2021-01-13 10:07 UTC, zigasinko commented on src/components/genexpress/modules/differentialExpressions/differentialExpressions.integration.spec.tsx
> +import { validateExportFile } from 'components/genexpress/common/reportBuilder/reportBuilder.integration.spec';
Thanks. Moved `validateExport` function to `test-utils.tsx`.

2021-01-13 10:30 UTC, zigasinko commented on src/components/genexpress/modules/differentialExpressions/differentialExpressionsVolcanoPlot.tsx
> +                {
Created a root scope function `getVegaSpecification` so that component is nice and short. Since these `...Plot.tsx` visualization components mostly include only Vega specification values and logic I left it in the same file.
Also fixed this in `geneExpressionsLineChart`.

2021-01-13 10:34 UTC, zigasinko commented on src/components/genexpress/modules/geneExpressions/geneExpressionsLineChart.tsx
> +        // Data handlers that is updated (and reattached) only if highlighted variable changes.
Added a custom function `useVariableMemo` and used it everywhere instead of misused `useMemo`.

2021-01-13 13:28 UTC, zigasinko commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> +    alert(
Agreed with Mihas that Safari <10.1 is considered unsupported and we don't need this warning anymore. Removed everything `old safari` related.

2021-01-13 13:53 UTC, zigasinko commented on src/components/genexpress/common/reportBuilder/reportBuilder.ts
> +        browser.getBrowserName() === 'safari' && !browser.satisfies({ safari: '>=10.1' });
^^above

2021-01-13 16:35 UTC, janybravo approved these changes

2021-01-14 11:16 UTC, merged