Hierarchical clustering
genialis/dictyexpress-js pull request #14
Opened 2020-12-01 11:31 UTC by zigasinko

2021-01-14 16:32 UTC, janybravo requested changes

2021-01-14 16:32 UTC, janybravo commented on src/api/queryObserverManager.ts
> + */
remove

2021-01-14 16:32 UTC, janybravo commented on src/api/queryObserverManager.ts
> + */
and all the rest

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/common/chart/chart.tsx
> +     */
remove

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/common/chart/chart.tsx
> +     */
and the rest

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.integration.spec.tsx
> +                    return Promise.resolve(
Promise.resolve(JSON.stringify(   repeats often, extract to util function. applies to all other usages

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.integration.spec.tsx
> +                    return Promise.resolve(
consider extraction complete WS mocking function if applicable.

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +    // Each time data changes, visualization data must be refreshed.
remove

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +        const intermediateTable: _.NumericDictionary<ClusterNode> = {}; // {[node: number]: {x, y, parent}}
comment is what type should be, remove comment or update type

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +            const middle = (intermediateTable[node1]?.y + intermediateTable[node2]?.y) / 2;
as type says middle could be NaN, and that doesnt seem to be handled. handle it please

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +             */
remove

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +     */
remove

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +     */
and same for other function describing JSDOC

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +    // Register reportBuilder getComponentReport function.
remove

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +            // clusteringNodes array is empty.
same

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clusteringChart.tsx
> +         * @param ids - Array of numbers that will be wrapped into an object with
@param ids?? remove type doc as it is confusing. note on vega is complementary to this code so it should stay

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/clustering/clusteringChart.tsx
> +        // Data handlers that is updated (and reattached) only if highlighted variable changes.
yes I can read that and some more from dependencies, remove

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/differentialExpressions/differentialExpressionsVolcanoPlot.tsx
> +            return !highestValueInData
invert expression to non-inverted one for redability

2021-01-14 16:32 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +        // Time series to be visualized.
remove all comments

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/clusteringEpics.ts
> + */
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/clusteringEpics.ts
> +const getOrCreateClusteringEpic = getOrCreateProcessDataEpics<ClusteringData>({
Seems like factory function producing singletons to me by its name. therefore perhaps `clusterProcessDataEpicFactory` ?

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/epicsActions.ts
> +// ClusteringEpics.
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/processEpics.ts
> + */
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/processEpics.ts
> +     */
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/processEpics.ts
> +     */
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/processEpics.ts
> +     */
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/epics/processEpics.ts
> +     */
and all of the same

2021-01-14 16:32 UTC, janybravo commented on src/redux/models/internal.ts
> +    }[];
Use `Array<T> `notation of Arrays for multiline `T` for readability. it can get confusing quickly at more complicated Array types.

2021-01-14 16:32 UTC, janybravo commented on src/redux/rootReducer.ts
> +// RootState selectors (expose root state to containers).
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/rootReducer.ts
> +        const newGenesExpressionsData = [] as GeneExpression[];
[] is always new instance meaning possible uneccessary re-render. use common `EMPTY_ARRAY` const possibly immutable to catch problems by unintentional mutation.

2021-01-14 16:32 UTC, janybravo commented on src/redux/rootReducer.ts
> +                timePointPartitions.forEach((partition) => {
.filter is better suited for the job thatn .forEach

2021-01-14 16:32 UTC, janybravo commented on src/redux/stores/clustering.ts
> +// State slices.
remove

2021-01-14 16:32 UTC, janybravo commented on src/redux/stores/clustering.ts
> +            (): MergedClusteringData => {
extract this to function or make it oneliner for other cases.

2021-01-14 16:32 UTC, janybravo commented on src/redux/stores/clustering.ts
> +const linkageFunctionInitialState = 'average' as ClusteringLinkageFunction;
Seems that should be an enum from constants

2021-01-14 16:32 UTC, janybravo commented on src/tests/mock.ts
> + */
remove

2021-01-15 09:12 UTC, zigasinko commented on src/api/queryObserverManager.ts
> + */
Removed.

2021-01-15 09:14 UTC, zigasinko commented on src/components/genexpress/common/chart/chart.tsx
> +     */
Removed all function comments inside Chart component.

2021-01-15 09:53 UTC, zigasinko commented on src/components/genexpress/modules/clustering/clustering.integration.spec.tsx
> +                    return Promise.resolve(
Extracted to `resolveStringifiedObjectPromise` test-utils and used everywhere.

2021-01-15 09:55 UTC, zigasinko commented on src/components/genexpress/modules/clustering/clustering.tsx
> +        const intermediateTable: _.NumericDictionary<ClusterNode> = {}; // {[node: number]: {x, y, parent}}
Updated type and removed comment.

2021-01-15 10:02 UTC, zigasinko commented on src/components/genexpress/modules/clustering/clustering.tsx
> +            const middle = (intermediateTable[node1]?.y + intermediateTable[node2]?.y) / 2;
Wrongly marked as "possibly null".

2021-01-15 10:05 UTC, zigasinko commented on src/components/genexpress/modules/clustering/clusteringChart.tsx
> +         * @param ids - Array of numbers that will be wrapped into an object with
A good example of why commenting everything isn't the best option.. changed function definition and didn't update the comment. Fix'd!

2021-01-15 10:06 UTC, zigasinko commented on src/components/genexpress/modules/clustering/clusteringChart.tsx
> +        // Data handlers that is updated (and reattached) only if highlighted variable changes.
Removed comment and used future proof `useStateWithEffect` instead of `useMemo`.

2021-01-15 10:09 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +        // Time series to be visualized.
Removed also from other components that had the same type of comments: `differentialExpressions`, `associationsModal`.

2021-01-15 10:20 UTC, zigasinko commented on src/redux/epics/clusteringEpics.ts
> +const getOrCreateClusteringEpic = getOrCreateProcessDataEpics<ClusteringData>({
Good one. This one is using the factory, so I've renamed `processEpics.ts` to `getProcessDataEpicsFactory.ts`. Also renamed function in:
- `clusteringEpics.ts` to `getClusteringProcessDataEpics`
- `gOEnrichmentEpics.ts` to `getGOEnrichmentProcessDataEpics`.

2021-01-15 10:20 UTC, zigasinko commented on src/redux/epics/epicsActions.ts
> +// ClusteringEpics.
Removed all this type of comments from `epicsActions.ts`.

2021-01-15 11:08 UTC, zigasinko commented on src/redux/rootReducer.ts
> +        const newGenesExpressionsData = [] as GeneExpression[];
Shouldn't be a problem because chart is only displayed if there is more than one expression in the array. Still, I've added a `EMPTY_ARRAY` and used it instead of `[]`.

2021-01-15 11:09 UTC, zigasinko commented on src/redux/stores/clustering.ts
> +// State slices.
Removed all these types of comments (`Export actions...`, `Selectors...`) from all stores!

2021-01-15 11:31 UTC, zigasinko commented on src/redux/stores/clustering.ts
> +const linkageFunctionInitialState = 'average' as ClusteringLinkageFunction;
You're right, it's cleaner with enums. I've moved all hardcoded types (`ClusteringLinkageFunction`, `ClusteringDistanceMeasure`, `AspectValue `and `ProcessSlug`) to enums.

2021-01-15 12:11 UTC, zigasinko commented on src/redux/stores/clustering.ts
> +            (): MergedClusteringData => {
Created a redux stores common function `clearStateOnActions` and used it in all stores that clear state on multiple actions (clustering, gOEnrichment, genes).

2021-01-15 15:35 UTC, janybravo commented on src/redux/rootReducer.ts
> +                timePointPartitions.forEach((partition) => {
nevermind this, cant be improved easyway

2021-01-15 15:36 UTC, janybravo approved these changes

2021-01-17 09:37 UTC, merged