Todos
genialis/dictyexpress-js pull request #15
Opened 2020-12-19 23:19 UTC by zigasinko

2021-01-18 09:20 UTC, janybravo requested changes

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.tsx
> +import GeneSelectorModalControls from 'components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelectorModalControls/geneSelectorModalControls';
this is inter module import, extract to common. treat "app" modules as independant from other modules "app modules". keep simple relations between "app" modules, no nested dependencies on other "app" modules  like this is.  Preffer dependants to "common" module

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.spec.tsx
> +                    return Promise.resolve(
you have that util function somewhere, replace all other cases

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +import GeneSelectorModalControls from 'components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelectorModalControls/geneSelectorModalControls';
this too

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +    return {
Consider extracting function and then its inferred type via ReturnType<typeof x>

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +    // Prepare data -> attach Gene to each similar gene distance.
remove along with others of such case

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +    const columnDefs = useRef([
to module root scope

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +                        type="button"
well is it ?

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +    const handleDisplayLegendOnChange = (event: ChangeEvent<HTMLInputElement>): void => {
to jsx

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +        setManageModalOpened(true);
to jsx

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelectorModalControls/geneSelectorModalControls.tsx
> +    /**
remove along with others

2021-01-18 09:20 UTC, janybravo commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/timeSeriesAndGeneSelector.tsx
>      const columnDefs = useRef([
to module root scope

2021-01-18 09:20 UTC, janybravo commented on src/redux/epics/findSimilarGenesEpics.ts
> +        // If similar genes are already in store, do not fetch them again.
remove

2021-01-18 09:20 UTC, janybravo commented on src/redux/epics/findSimilarGenesEpics.ts
> +        // Query gene is mandatory to find it's similar genes.
remove

2021-01-18 09:20 UTC, janybravo commented on src/redux/epics/findSimilarGenesEpics.ts
> +/**
remove

2021-01-18 09:20 UTC, janybravo commented on src/redux/epics/findSimilarGenesEpics.ts
> +        genesSimilaritiesFetchSucceeded(storage.json['similar genes']),
user enum for storage keys

2021-01-18 09:20 UTC, janybravo commented on src/redux/epics/findSimilarGenesEpics.ts
> +            // similarGenesQueryGeneSelected
remove

2021-01-18 09:20 UTC, janybravo commented on src/redux/models/internal.ts
> +/**
remove

2021-01-18 09:20 UTC, janybravo commented on src/utils/errorUtils.ts
> + * Send the error to Sentry and return "addErrorSnackbar" action. If associatedObject is
remove all JSDOC

2021-01-18 09:20 UTC, janybravo commented on src/utils/sentryUtils.ts
> +/**
remove all jsdoc

2021-01-19 10:36 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/associationsModal/associationsModal.tsx
> +import GeneSelectorModalControls from 'components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelectorModalControls/geneSelectorModalControls';
Moved `GeneSelectorModalControls ` to genexpress/common.

2021-01-19 10:38 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +import GeneSelectorModalControls from 'components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/geneSelectorModalControls/geneSelectorModalControls';
Moved `GeneSelectorModalControls` to genexpress/common.

2021-01-19 10:54 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +    return {
`mapStateToProps` already is such a function. All `mapStateToProps` functions could be written without defined return type and it will infer it. But that means disabling `explicit-function-return-type` eslint rule which is fine. I've removed return type from all `mapStateToProps` functions in codebase.

2021-01-19 11:12 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +    const columnDefs = useRef([
Done. Besides this one, I've also moved all other "static" columnDefs to root scope.

2021-01-19 11:17 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +                        type="button"
That's why it's written twice :D It's good practice to always define button type and even enforced with ESlint for regular `<button />` elements: [https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md).

2021-01-19 11:20 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +    const handleDisplayLegendOnChange = (event: ChangeEvent<HTMLInputElement>): void => {
Done. Also moved `handleFindSimilarOnClick` which only sets `manageModalOpened(true)`.

2021-01-19 11:21 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +        setManageModalOpened(true);
Haha, already done ^^above.

2021-01-19 11:30 UTC, zigasinko commented on src/redux/epics/findSimilarGenesEpics.ts
> +        genesSimilaritiesFetchSucceeded(storage.json['similar genes']),
It would be better to extend `Storage` type in resolwe-js. But that would be a looooooot of work for a little improvement. I suggest we leave it as is and fix the types in expressions-ui.

2021-01-20 09:41 UTC, janybravo commented on src/redux/epics/findSimilarGenesEpics.ts
> +        genesSimilaritiesFetchSucceeded(storage.json['similar genes']),
Ok, scheduled for Expressions project then

2021-01-20 09:46 UTC, janybravo approved these changes

2021-01-20 13:00 UTC, merged