Experiment comparison
genialis/dictyexpress-js pull request #18
Opened 2021-01-08 09:09 UTC by zigasinko

2021-01-20 13:17 UTC, janybravo requested changes

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.spec.tsx
> +                        JSON.stringify({
reuse util function

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/findSimilarGenesModal.tsx
> +    const handleDistanceMeasureChange = (event: ChangeEvent<{ value: unknown }>): void => {
move to jsx

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/toDictybaseCell/toDictybaseCell.tsx
> +        <>
unecessary

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +                            type="button"
remove this and other cases

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +                            genesExpressions={[...genesExpressions, ...comparisonGenesExpressions]}
this means new instance each render that could potetialy case bad performance. consider not generating new instances on render.

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/selectComparisonTimeSeriesModal/selectComparisonTimeSeriesModal.spec.tsx
> +        // fireEvent.click(await screen.findByText(timeSeries[0].collection.name));
why this ?

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/selectComparisonTimeSeriesModal/selectComparisonTimeSeriesModal.tsx
> +const mapStateToProps = (
use Return<type X>

2021-01-20 13:17 UTC, janybravo commented on src/components/genexpress/modules/genesExpressions/selectComparisonTimeSeriesModal/selectComparisonTimeSeriesModal.tsx
> +                            timeSeries={timeSeries.filter(
consider not filtering timeSeries at render

2021-01-25 08:14 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/findSimilarGenesModal/toDictybaseCell/toDictybaseCell.tsx
> +        <>
Removed unnecessary `<>` and `return` from this and other custom cell components (`matchedCell`, `scoreCell`, `termCell`).

2021-01-25 10:35 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +                            type="button"
Removed because material-ui adds `type="button"` by default. Thanks.

2021-01-25 11:01 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
> +                            genesExpressions={[...genesExpressions, ...comparisonGenesExpressions]}
Good improvement! Moved setting `allGenesExpressions` to `useStateWithEffect`.

2021-01-25 11:01 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/selectComparisonTimeSeriesModal/selectComparisonTimeSeriesModal.spec.tsx
> +        // fireEvent.click(await screen.findByText(timeSeries[0].collection.name));
Mistakes.. regrets!!! Removed.

2021-01-25 11:04 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/selectComparisonTimeSeriesModal/selectComparisonTimeSeriesModal.tsx
> +                            timeSeries={timeSeries.filter(
Moved filtering time series to `useStateWithEffect`.

2021-01-25 13:14 UTC, janybravo approved these changes

2021-01-25 13:41 UTC, merged