Bookmarks
genialis/dictyexpress-js pull request #21
Opened 2021-01-27 11:30 UTC by zigasinko

2021-02-12 11:25 UTC, janybravo requested changes

2021-02-12 11:25 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +            if (mergedData != null) {
Lets use strict inequality/equality in all our code. That way is easier to reason about outcome of expressions (avoiding some of JS grabage). Eg. here you should note that `null  == undefined` is `true` and god of ECMA knows what else.

2021-02-12 11:25 UTC, janybravo commented on src/components/genexpress/common/useBookmarkableState.ts
> +    bookmarkStatePath: string,
Consider Enum type for all paths.

2021-02-12 11:25 UTC, janybravo commented on src/managers/bookmarkStateManager.ts
> +const registeredBookmarkableStates: {
Consider using Map<T><string, T>

2021-02-12 11:25 UTC, janybravo commented on src/redux/epics/samplesExpressionsEpics.ts
> + */
remove

2021-02-12 11:25 UTC, janybravo commented on src/redux/epics/samplesExpressionsEpics.ts
> +            // Fetch only samples expressions that aren't in redux store yet.
remove

2021-02-12 11:25 UTC, janybravo commented on src/redux/epics/samplesExpressionsEpics.ts
> +            // If all samples expressions in question are already in store, there's no need to fetch them again!
remove

2021-02-12 11:25 UTC, janybravo commented on src/redux/rootReducer.ts
> +        // If any of samplesExpressions isn't in store
remove

2021-02-12 11:25 UTC, janybravo commented on src/utils/url.ts
> +export const updateUrlParameter = (originalUri: string, key: string, value: string): string => {
Seems that is browsers already have and what should go instead of url.ts, see https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set

2021-02-15 08:44 UTC, zigasinko commented on src/components/genexpress/modules/clustering/clustering.tsx
> +            if (mergedData != null) {
Using non-strick inequality check is done on purpose because it correctly handles both cases `null` and `undefined`. There's also an eslint rule enforcing this everywhere except on `null` checks.

2021-02-15 08:48 UTC, zigasinko commented on src/managers/bookmarkStateManager.ts
> +const registeredBookmarkableStates: {
Is `Map<string, T>` a TypeScript utility (I don't find it) or did you think I'd write it myself?

2021-02-15 09:10 UTC, zigasinko commented on src/utils/url.ts
> +export const updateUrlParameter = (originalUri: string, key: string, value: string): string => {
Nice one. Used this approach and removed `url.ts` util file.

2021-02-15 09:21 UTC, janybravo commented on src/managers/bookmarkStateManager.ts
> +const registeredBookmarkableStates: {
its JS type not an util, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

2021-02-15 09:28 UTC, zigasinko commented on src/components/genexpress/common/useBookmarkableState.ts
> +    bookmarkStatePath: string,
Added enum `BookmarkStatePath` with paths to components specific bookmarkable state.

2021-02-15 09:28 UTC, janybravo commented on src/components/genexpress/modules/clustering/clustering.tsx
> +            if (mergedData != null) {
understood

2021-02-15 09:52 UTC, zigasinko commented on src/managers/bookmarkStateManager.ts
> +const registeredBookmarkableStates: {
Ohh.. here only a few components states are pushed into `registeredBookmarkableStates` so performance for a lot of values isn't a problem. All references are done via string key, ordering isn't necessary. That's why I'd rather stick with the same principle used in other places (e.g. components registering to report manager / normalized states) and go with object.

2021-02-15 11:01 UTC, janybravo commented on src/managers/bookmarkStateManager.ts
> +const registeredBookmarkableStates: {
Its not a performance problem, its an convinence because you have cleaer syntax offered by Map with already existing set of methods. Lets preffer that in future app.

2021-02-15 11:03 UTC, janybravo approved these changes

2021-02-15 11:14 UTC, merged