Add Github Actions build workflow
genialis/dictyexpress-js pull request #40
Opened 2022-03-18 13:30 UTC by acopar

2022-03-21 08:34 UTC, gregorjerse approved these changes

2022-03-21 08:48 UTC, gregorjerse requested changes
Please change node version: 16.x is not supported.

Or upgrade packages: at least `node-sass` to version `>= 6.0.1`.

2022-03-21 09:02 UTC, gregorjerse approved these changes
After upgrading packages this should be ok.

2022-03-24 09:36 UTC, acopar commented
Superseded by #39

2022-03-24 09:37 UTC, closed without merging