Optimizations
genialis/dictyexpress-js pull request #48
Opened 2022-08-12 09:22 UTC by plojyon

2022-08-25 11:18 UTC, zigasinko commented on src/components/genexpress/modules/timeSeriesAndGeneSelector/geneSelector/selectedGenes/geneInformation/__snapshots__/geneInformation.spec.tsx.snap
> +        Gene ID:
Alternatives should also be displayed. Add GeneID above it.

2022-08-25 11:29 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressionsLineChart.tsx
> +                                    test: "indata('comparison', 'timeSeriesName', datum.timeSeriesName)",
Refactor so that `genesExpressionsLineChart` receives `comparisonTimeSeries` not their expressions and make this test depend on the name in `comparisonTimeSeries`. Otherwise things can get slow if `comparisonTimeSeriesExpressions` is a large array.

2022-08-25 11:30 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressionsLineChart.tsx
> +    comparisonGenesExpressions: GeneExpression[];
Don't forget to rename this back when `comparisonTimeSeries` is passed on as a property.

2022-08-25 11:47 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
>                  {genesExpressions.length > 0 && (
Let's add a unit test for this feature. In the comparison describe block, add a check for dash strokes.
Something along the lines:
```
await waitFor(() => {
      const linesStrokeDashArrays = getLinesDashArrays();   // similar to getLinesColors
      expect(linesStrokeDashArrays[0]).toBeUndefined;
      expect(linesStrokeDashArrays[1]).toBe([8, 8;]);
  });
```

2022-08-25 11:48 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.tsx
>                  {genesExpressions.length > 0 && (
We can do it together if you run into any troubles.

2022-08-25 11:50 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    type CollapsedData = { [key: string]: { hidden: boolean; manuallyCollapsed: boolean } };
All good, I used to write this the same way. A bit better is to use TypeScript helper function:
`Record<string, { hidden: boolean; manuallyCollapsed: boolean }>`.

2022-08-25 11:53 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +    const getRowId = (data: GOEnrichmentRow, path: string[]) => {
Static functions not dependent on any parent variables (everything the function needs, it receives in the parameters), should be outside of the component. So, put it into gOEnrichment utils or above `const GOEnrichment...`.

2022-08-25 12:06 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
>          [getSort, treeView],
`onToggleCollapseClickHandler` uses `getRow` function which is recreated on each render. `columnDefs` is created only when `getSort` and `treeView` reference changes. So, what could happen is that `getSort` is changed but `columnDefs` are still bound to the old one.
When you will move `getRowId` outside the component, everything will be good because `onToggleCollapseClickHandler` will only use static - not changable functions.

Hope that this helps you make sense of this dependency principles.

2022-08-25 12:08 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/gOEnrichment.tsx
> +                            data={getDisplayedRows()}
This will still execute on each render. It's better to memoize expensive operations. Use `useStateWithEffect` to create `displayedRows`.

2022-08-25 12:15 UTC, zigasinko commented on src/components/genexpress/modules/gOEnrichment/termCell/termCell.styles.ts
> +    $haschildren: boolean;
Rename `$haschildren` to `$hasChildren`.

2022-08-31 11:14 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.integration.spec.tsx
> +            .filter((value, index, self) => self.indexOf(value) == index); // filter unique values
Using a function to retrieve only unique values is more explicit - lodash `uniq`.
It's also perfectly ok to leave it the way you implemented it, just move the comment in a line above and write it capitalized with a period at the end.
And change `==` to `===`. Read about difference between both, e.g.: [https://www.guru99.com/difference-equality-strict-operator-javascript.html](https://www.guru99.com/difference-equality-strict-operator-javascript.html)

ESLint gave a warning about it, let's keep our code warnings free, they are there for a reason. So, fix all the rest also.

2022-08-31 11:19 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressions.integration.spec.tsx
> +            await waitFor(() => {
No need to have `waitFor` here, because the chart being rendered is enforced in the `beforeEach` block (`await validateChart()`).

2022-08-31 11:24 UTC, zigasinko commented on src/redux/stores/timeSeries.ts
> +            .map((timeSeries) => ({...timeSeries, timeSeriesName: timeSeries.collection.name }));
If it's possible to access "datum.collection.name" in vega `indata` function, there's no need for a redundant property `timeSeriesName`.

2022-08-31 11:30 UTC, zigasinko commented on src/api/differentialExpressionApi.ts
> +        tags: `community:${COMMUNITY_SLUG}`,
As stated in the ticket, add ```tags: `community:${COMMUNITY_SLUG}` ``` to `getTimeSeriesRelations` so that the user only receives relations  from the relevant community (e.g. "bcm" - Baylor college of medicine).

2022-08-31 11:34 UTC, zigasinko requested changes
Looking good! A few minor things to take care of and we're ready for merge.
Don't forget to fix all lint warnings (if "any" type can't be replaced with a specific type or "unknown", make an ESLint exception for those lines).

2022-09-01 09:44 UTC, plojyon commented on src/api/differentialExpressionApi.ts
> +        tags: `community:${COMMUNITY_SLUG}`,
The tags parameter is currently unsupported for the relation API.

2022-09-02 08:05 UTC, zigasinko commented on src/components/genexpress/modules/genesExpressions/genesExpressionsLineChart.tsx
> +                    // At least as of Firefox 48, the ⊞ Windows key is no longer considered a metaKey.
Good comment.

2022-09-02 08:06 UTC, zigasinko approved these changes

2022-09-05 09:07 UTC, merged